import { cardFrame } from './CardShell'
import type { ReactNode } from 'react'
import type { CardPayload } from '@/lib/markdown/link-cards/types'

// No link affordances: only the header row is an anchor.
const frameClass = `${cardFrame} file-card overflow-hidden`

/**
 * File card: linked header + shiki-highlighted content. Body is a plain
 * div (not part of the link) so code stays selectable.
 */
export const FileCard = ({
  card,
  icon,
  project,
  file,
}: {
  card: CardPayload
  icon: ReactNode
  project: string
  file: string
}) => {
  const { url, info, meta } = card
  const range = info.lineStart
    ? `L${info.lineStart}${info.lineEnd ? `-L${info.lineEnd}` : ''}`
    : null

  const header = (
    <a
      href={url}
      target="_blank"
      rel="noopener noreferrer"
      className="flex items-center gap-3 px-4 py-3 no-underline transition-colors hover:bg-base-300"
    >
      <span className="shrink-0 opacity-60">{icon}</span>
      <span className="min-w-0 flex-1 truncate font-mono text-sm font-semibold">
        {file}
        {range && <span className="opacity-60">:{range}</span>}
      </span>
      <span className="shrink-0 text-xs opacity-60">
        {project} @ {info.ref}
      </span>
    </a>
  )

  if (!meta?.codeHtml) {
    // Fetch failed or host not whitelisted — header row only
    return <div className={frameClass}>{header}</div>
  }

  return (
    <div className={frameClass}>
      {header}
      <div
        className="max-h-96 overflow-auto border-t border-base-300 text-sm"
        // Server-generated by shiki from the fetched file — shiki escapes
        // all content.
        dangerouslySetInnerHTML={{ __html: meta.codeHtml }}
      />
      {meta.extra?.total && (
        <a
          href={url}
          target="_blank"
          rel="noopener noreferrer"
          className="block border-t border-base-300 px-4 py-2 text-center text-xs no-underline opacity-60 transition-opacity hover:opacity-100"
        >
          Showing first {meta.extra.shown} of {meta.extra.total} lines — view
          full file
        </a>
      )}
    </div>
  )
}
